### ISSUE TITLE
Question: Where do you put the settings file under?

### ISSUE THREAD

**Issue by vnoxygen** [thorgate/django-project-template#5]
Hi 

I kept on receiving the following error:
`django_1    | Couldn't import settings.local, have you created it from settings/local.py.example ?`

I have moved the sample copy django-project-template\<project>\<project> with different iterations of file name: "settings.py" , "settings.local", and etc.

Am I missing something here, what is the settings file name should it be? and which directory should it falls under?

**Comment by metsavaht** [comment]
Hi.

After generating a project. Copy `<project>/<project>/settings/local.py.example` to `<project>/<project>/settings/local.py`.

**Comment by vnoxygen** [comment]
`<project>/<project>/settings/local.py` works! thanks @metsavaht
