### ISSUE TITLE
Question: how to make migrations on each docker-compose up

### ISSUE THREAD

**Issue by vnoxygen** [thorgate/django-project-template#6]
I am getting the below error, but how do I automatically "python manage.py migrate" before runserver from docker-compose?

`You have unapplied migrations; your app may not work properly until they are applied. @ #`

**Comment by vnoxygen** [comment]
Ended up copying another script and adding `command: ["bash", "/usr/bin/wait-for-it.sh", "postgres:5432", "--", "/usr/bin/docker-entrypoint.sh"]` into docker-compose. Any other 'smarter' workaround?


/usr/bin/docker-entrypoint.sh
`#!/bin/bash

# Collect static files
echo "Collect static files"
python manage.py collectstatic --noinput

# Apply database migrations
echo "Apply database migrations"
python manage.py migrate --noinput

# Start server
echo "Starting server"
python manage.py runserver 0.0.0.0:80`

**Comment by raunofreiberg** [comment]
You can just run the migrations via `make migrate` before doing `docker-compose up` or `make docker`. Don't see why you would want to run them concurrently.

**Comment by metsavaht** [comment]
In top level there is Makefile with bunch of helpers e.g `<project>/Makefile`
This info should also be described in `README` as well.

**Comment by vnoxygen** [comment]
@raunofreiberg you are right, it was a "at-that-moment" solution when trying to figure out docker and django at the same time. But I did bump into the same point to separate the migrate and docker-compse up workflows.

@metsavaht I think I can see [Docker Python Makefile](https://github.com/thorgate/django-project-template/tree/docker/%7B%7Bcookiecutter.repo_name%7D%7D) mentioned, definitely what I am looking for:

make migrations | make makemigrations cmd=<command> | docker-compose run --rm django ./manage.py makemigrations $(cmd)
-- | -- | --
migrating | make migrate cmd=<command> | docker-compose run --rm django ./manage.py migrate $(cmd)

thanks folks!
